package email

import (
	"bytes"
	"strings"
	"testing"
	"time"
)

func TestOverviewHTMLHumanizesLargeNumbers(t *testing.T) {
	in := OverviewInput{View: OverviewView{
		Tenant:      "acme",
		GeneratedAt: time.Date(2026, 5, 17, 10, 30, 0, 0, time.UTC),
		Totals: OverviewTotals{
			UserCount: 1234, DeviceCount: 5678, TotalIssues: 18553,
			Critical: 1100, High: 2200, Medium: 4321, Low: 10932,
			SecScore: 87654.32,
		},
		Averages: OverviewAverages{
			DevicesPerUser: 4.6, IssuesPerUser: 15.0, SecScorePerUser: 71.0,
		},
		BestFive: []UserStats{
			{UserID: "u1", Rank: 1, Name: "Alice", SecScore: 12345.67, Critical: 100, High: 200},
		},
		MostDangerousFive: []UserStats{
			{UserID: "u1", Rank: 1, Name: "Alice", SecScore: 12345.67, Critical: 100, High: 200},
		},
		Users: []UserStats{
			{UserID: "u1", Rank: 1, Name: "Alice", SecScore: 12345.67, Critical: 100, High: 200, DeviceCount: 1234, TotalIssues: 9876},
		},
	}}
	data := buildOverviewTplData(in.View, newOverviewOptions())
	got, err := renderOverviewHTML(data)
	if err != nil {
		t.Fatalf("renderOverviewHTML: %v", err)
	}
	for _, want := range []string{
		">1,234<",    // UserCount stat card
		">5,678<",    // DeviceCount stat card
		">18,553<",   // TotalIssues stat card
		">87,654.3<", // Totals SecScore stat card
		">1,100<",    // Critical stat card
		">2,200<",    // High stat card
		">4,321<",    // Medium stat card
		">10,932<",   // Low stat card
		">12,345.7<", // per-row ScoreStr in leaderboard / roster
		"C 100",      // severity pill on a row
		"H 200",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("HTML missing %q", want)
		}
	}
}

func newOverviewInputAdmin() OverviewInput {
	return OverviewInput{View: OverviewView{
		Tenant:      "acme",
		GeneratedAt: time.Date(2026, 5, 17, 10, 30, 0, 0, time.UTC),
		Totals: OverviewTotals{
			UserCount: 2, DeviceCount: 3, TotalIssues: 4, Critical: 1, High: 1, Medium: 1, Low: 1, SecScore: 24.8,
		},
		Averages: OverviewAverages{
			DevicesPerUser: 1.5, IssuesPerUser: 2.0, SecScorePerUser: 12.4,
			CriticalPerUser: 0.5, HighPerUser: 0.5, MediumPerUser: 0.5, LowPerUser: 0.5,
		},
		BestFive: []UserStats{
			{UserID: "u-bob", Rank: 2, Name: "Bob", SecScore: 2.5, Critical: 0, High: 0, Medium: 0, Low: 1},
			{UserID: "u-alice", Rank: 1, Name: "Alice", SecScore: 22.3, Critical: 1, High: 1, Medium: 1, Low: 0},
		},
		MostDangerousFive: []UserStats{
			{UserID: "u-alice", Rank: 1, Name: "Alice", SecScore: 22.3, Critical: 1, High: 1, Medium: 1, Low: 0},
			{UserID: "u-bob", Rank: 2, Name: "Bob", SecScore: 2.5, Critical: 0, High: 0, Medium: 0, Low: 1},
		},
		Users: []UserStats{
			{UserID: "u-alice", Rank: 1, Name: "Alice", SecScore: 22.3, Critical: 1, High: 1, Medium: 1, Low: 0, DeviceCount: 2, TotalIssues: 3},
			{UserID: "u-bob", Rank: 2, Name: "Bob", SecScore: 2.5, Critical: 0, High: 0, Medium: 0, Low: 1, DeviceCount: 1, TotalIssues: 1},
		},
	}}
}

func newOverviewOptions() Options {
	return Options{
		To:                      "ops@example.com",
		From:                    "noreply@example.com",
		Subject:                 "Test overview",
		GeneratedAt:             time.Date(2026, 5, 17, 10, 30, 0, 0, time.UTC),
		Tenant:                  "acme",
		Report:                  "overview",
		BoundaryOverride:        "boundary-fixed",
		MessageIDOverride:       "<fixed@example.com>",
		RelatedBoundaryOverride: "related-fixed",
	}
}

func TestOverviewHTMLAdminBody(t *testing.T) {
	in := newOverviewInputAdmin()
	opts := newOverviewOptions().withDefaults()
	data := buildOverviewTplData(in.View, opts)
	got, err := renderOverviewHTML(data)
	if err != nil {
		t.Fatalf("renderOverviewHTML: %v", err)
	}
	for _, want := range []string{
		"The best 5",
		"The most dangerous 5",
		"All users",
		"Generated by jellyfish overview",
		"Sec score",
		"C 1", "H 1", "M 1", "L 1",
		"22.3", "2.5",
		"Alice", "Bob",
		"Sec Score</strong> is the sum of CVSS scores",
		"Lower is better.",
		">Sec Score</td>",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("admin HTML body missing %q", want)
		}
	}
	if strings.Contains(got, "Your standing") {
		t.Errorf("admin HTML body must not contain %q", "Your standing")
	}
}

func TestOverviewRendererAdminEnvelope(t *testing.T) {
	var buf bytes.Buffer
	if err := NewOverviewRenderer(newOverviewOptions()).Render(&buf, newOverviewInputAdmin()); err != nil {
		t.Fatalf("Render: %v", err)
	}
	got := buf.String()
	for _, want := range []string{
		"From: noreply@example.com",
		"To: ops@example.com",
		"Subject: Test overview",
		"X-Jellyfish-Report: overview",
		"X-Jellyfish-Tenant: acme",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("admin .eml envelope missing %q", want)
		}
	}
}

func TestOverviewHTMLPerUserBody(t *testing.T) {
	in := newOverviewInputAdmin()
	// Mark Alice as the recipient.
	in.View.Me = &in.View.Users[0]

	data := buildOverviewTplData(in.View, newOverviewOptions())
	got, err := renderOverviewHTML(data)
	if err != nil {
		t.Fatalf("renderOverviewHTML: %v", err)
	}

	for _, want := range []string{
		"Your standing",       // callout label
		"1st",                 // ordinal rank
		"of 2",                // "of N"
		"background:#eff6ff;", // YOU-row tint on the roster row
		"background:#dcfce7;", // YOU-row tint in The best 5
		"background:#fee2e2;", // YOU-row tint in The most dangerous 5
		">you</span>",         // YOU pill (lowercased in the template; text-transform makes it uppercase visually)
		"#2563eb",             // blue border / colour somewhere in the rendered HTML
		"Sec Score</strong> is the sum of CVSS scores", // explainer still present
		">Sec Score</td>", // column header still present
	} {
		if !strings.Contains(got, want) {
			t.Errorf("per-user HTML missing %q", want)
		}
	}
}
