package email

import (
	"bytes"
	"strings"
	"testing"
	"time"
)

// stripQPSoftBreaks removes quoted-printable soft line breaks (=\r\n and =\n)
// so that strings.Contains can match across QP-wrapped lines.
func stripQPSoftBreaks(s string) string {
	s = strings.ReplaceAll(s, "=\r\n", "")
	s = strings.ReplaceAll(s, "=\n", "")
	return s
}

func newOverviewInputAdmin() OverviewInput {
	return OverviewInput{View: OverviewView{
		Tenant:      "acme",
		GeneratedAt: time.Date(2026, 5, 17, 10, 30, 0, 0, time.UTC),
		Totals: OverviewTotals{
			UserCount: 2, DeviceCount: 3, TotalIssues: 4, Critical: 1, High: 1, Medium: 1, Low: 1, SecScore: 24.8,
		},
		Averages: OverviewAverages{
			DevicesPerUser: 1.5, IssuesPerUser: 2.0, SecScorePerUser: 12.4,
			CriticalPerUser: 0.5, HighPerUser: 0.5, MediumPerUser: 0.5, LowPerUser: 0.5,
		},
		BestFive: []UserStats{
			{UserID: "u-bob", Rank: 2, Name: "Bob", SecScore: 2.5, Critical: 0, High: 0, Medium: 0, Low: 1},
			{UserID: "u-alice", Rank: 1, Name: "Alice", SecScore: 22.3, Critical: 1, High: 1, Medium: 1, Low: 0},
		},
		MostDangerousFive: []UserStats{
			{UserID: "u-alice", Rank: 1, Name: "Alice", SecScore: 22.3, Critical: 1, High: 1, Medium: 1, Low: 0},
			{UserID: "u-bob", Rank: 2, Name: "Bob", SecScore: 2.5, Critical: 0, High: 0, Medium: 0, Low: 1},
		},
		Users: []UserStats{
			{UserID: "u-alice", Rank: 1, Name: "Alice", SecScore: 22.3, Critical: 1, High: 1, Medium: 1, Low: 0, DeviceCount: 2, TotalIssues: 3},
			{UserID: "u-bob", Rank: 2, Name: "Bob", SecScore: 2.5, Critical: 0, High: 0, Medium: 0, Low: 1, DeviceCount: 1, TotalIssues: 1},
		},
	}}
}

func newOverviewOptions() Options {
	return Options{
		To:                      "ops@example.com",
		From:                    "noreply@example.com",
		Subject:                 "Test overview",
		GeneratedAt:             time.Date(2026, 5, 17, 10, 30, 0, 0, time.UTC),
		Tenant:                  "acme",
		Report:                  "overview",
		BoundaryOverride:        "boundary-fixed",
		MessageIDOverride:       "<fixed@example.com>",
		RelatedBoundaryOverride: "related-fixed",
	}
}

func TestOverviewRendererAdminGolden(t *testing.T) {
	var buf bytes.Buffer
	if err := NewOverviewRenderer(newOverviewOptions()).Render(&buf, newOverviewInputAdmin()); err != nil {
		t.Fatalf("Render: %v", err)
	}
	got := stripQPSoftBreaks(buf.String())

	// Spot checks that the admin variant is right.
	for _, want := range []string{
		"From: noreply@example.com",
		"To: ops@example.com",
		"Subject: Test overview",
		"X-Jellyfish-Report: overview",
		"X-Jellyfish-Tenant: acme",
		"Security overview",       // title in header partial
		"The best 5",              // section label
		"The most dangerous 5",
		"All users",
		"Alice", "Bob",
		"22.3", "2.5",             // formatted SecScore values
		"Sec score",               // stat-card label (HTML body)
		"C 1", "H 1", "M 1", "L 1", // severity pills
		"Generated by jellyfish overview",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("admin .eml missing %q", want)
		}
	}
	for _, unwanted := range []string{
		"Your standing", // admin must NOT have the per-user callout
	} {
		if strings.Contains(got, unwanted) {
			t.Errorf("admin .eml should not contain %q", unwanted)
		}
	}
}
